### ISSUE TITLE
use set: after a real word will remove the word

### ISSUE THREAD

**Issue by zhangshea** [inns/mak#1]
like when in edit mode and
`
hello siriset:
`
and select split will remove the word "siri"

**Comment by quietshu** [comment]
Thanks for reporting. Can you reproduce this issue on [mak.ink](mak.ink) after reloading the Service Worker?
To reload the Service Worker (on Google Chrome), open the Application panel in Developer Tool and choose Service Workers, click `unregister` for the Service Worker on mak.ink. Then refresh the page.

**Comment by zhangshea** [comment]
After reloading the Service Worker, it seems okay. It will not trigger the set function when you type  `hello siriset:` and only trigger when type exact `set:` like `hello siri set:`. That's okay.

**Comment by zhangshea** [comment]
And btw, the url in your reply could not jump to the real position. I think this issue could be closed.

**Comment by quietshu** [comment]
Big thanks :))
