### ISSUE TITLE
can't change text in [] when in the file list page.

### ISSUE THREAD

**Issue by Doeye1997** [inns/mak#13]
can't change text in [] when in the file list page.
And a gist I have deleted still appear in my flie list.

**Comment by quietshu** [comment]
#
> can't change text in [] when in the file list page. 

Built-in pages are not editable (list, preferences, sample, profile).

#

> And a gist I have deleted still appear in my flie list. 

You probably need to delete the content (`mak.ink#your_gist_id`).
