### ISSUE TITLE
It is keep Redirecting... in windows10

### ISSUE THREAD

**Issue by harryisfish** [inns/mak#21]
When I try to log in and typed my Github's account and password, it stays on a blank page with "Redirecting..." title.

**Comment by julianbenegas** [comment]
Same. It looks like a Firebase Auth settings thing.

In the URL: `error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.`

**Comment by XmchxUp** [comment]
hi, guys, has the problem been solved?

**Comment by XmchxUp** [comment]
I have the same problem, how to solve it?

**Comment by harryisfish** [comment]
no

**Comment by XmchxUp** [comment]
Just now, I cleaned the chrome buffer. Then.......

**Comment by AnabasisXu** [comment]
> Just now, I cleaned the chrome buffer. Then.......

doesn't work for me

**Comment by mmcguffi** [comment]
I also have this issue, both with Mak-mini and mak.ink -- Mak seems very useful, though as far as I can tell it seems to be broken across platforms

**Comment by thisisreallife** [comment]
Same issue with me. On macOS, I cleared my chrome history so mak.ink is not sync with cloud. When I attempt to login, mak.ink always shows redirecting. 
The link of redirecting window is: `https://mak-auth.vercel.app/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=15916`

**Comment by shuding** [comment]
This is fixed now, my apologize for the inconvenience! 🙏
