### ISSUE TITLE
Button or shortcut for open preview

### ISSUE THREAD

**Issue by juandc** [inns/mak#5]
I did need to search into the documentation for  the split parameter in the url. Probably a button or a shortcut at least could make it more intuitive :open_mouth: :+1:

**Comment by quietshu** [comment]
Adding a button to toggle edit/split mode is nice. ✨
Thank you!!

**Comment by quietshu** [comment]
Click the version button and refresh the browser to update to v0.4.3, you can then find the "toggle preview" button 🎉
