### ISSUE TITLE
in safari by iOS, can't return pure edit status.

### ISSUE THREAD

**Issue by SolidZORO** [inns/mak#9]
in safari by iOS

can't return pure edit status,

and cant't selected text (editer is HTLM editable?)

![da0ec056-5034-4ba3-a22d-ac2c81a6c08a](https://user-images.githubusercontent.com/661587/53690208-3f261480-3da1-11e9-9324-f0e4221e1f00.png)

**Comment by quietshu** [comment]
The editor doesn’t work well on mobile currently. It is built on top of CodeMirror and I turned off contenteditable mode for mobile (which can’t handle IME correctly: https://github.com/codemirror/CodeMirror/issues/3137).

I look forward to seeing a better solution in the future. But right now both CodeMirror and Monaco are buggy on mobile.

**Comment by SolidZORO** [comment]
OK, I get. thanks.
